import json
import os
import sys
import numpy as np
import librosa
import tgt
import soundfile as sf
from datetime import datetime
from difflib import SequenceMatcher
from typing import List, Dict, Tuple, Optional

# Add DataSynthesizer root to path for cross-package imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from utils.vocoders import invert_mel_to_audio, mel_to_soulx_mel, SOULX_MEL_CONFIG

def extract_features_and_timings(
    prior_audio_path: str,
    target_audio_path: str,
    prior_textgrid_path: str,
    target_textgrid_path: str,
    config: Dict[str, int],
    segmentation_mode: str = "word",
    vocoder: str = "griffin_lim",
    target_mel_path: Optional[str] = None
) -> Tuple[np.ndarray, np.ndarray, List[Dict[str, float]], List[Dict[str, float]]]:
    """
    Loads audio, computes mel-spectrograms, and parses timing data.
    
    Args:
        prior_audio_path: Path to the prior audio file (e.g., OpenUtau output).
        target_audio_path: Path to the target audio file (e.g., SoulX-Singer output).
        prior_timings: Engine timings, e.g., [{'phoneme': 'a', 'start': 0.1, 'end': 0.3}].
        target_textgrid_path: Path to the MFA-generated TextGrid. (Optional)
        config: STFT parameters (sample_rate, n_fft, hop_length, n_mels).
        
    Returns:
        prior_mel: Mel-spectrogram of the prior audio (shape: mels x time).
        target_mel: Mel-spectrogram of the target audio.
        prior_boundaries_sec: List of dictionaries with phoneme boundaries in seconds.
        target_boundaries_sec: List of dictionaries with phoneme boundaries in seconds.
    """
    sr = config.get("sample_rate", 22050)
    n_fft = config.get("n_fft", 1024)
    hop_length = config.get("hop_length", 256)
    n_mels = config.get("n_mels", 80)
    
    y_prior, _ = librosa.load(prior_audio_path, sr=sr)
    y_target, _ = librosa.load(target_audio_path, sr=sr)
    
    # When using a pre-extracted mel (e.g., from SoulX-Singer's generator), load it directly.
    if target_mel_path and os.path.exists(target_mel_path):
        print(f"Loading pre-extracted post-mel from {target_mel_path}...")
        target_mel = np.load(target_mel_path)
        # Should be (Time, Mels) as generated by SoulX CLI, so transpose if needed.
        if target_mel.shape[1] == 128:
            target_mel = target_mel.T
        
        # We still need to extract prior_mel
        if vocoder == "soulxsinger":
            prior_mel = mel_to_soulx_mel(y_prior, sr=sr)
            hop_length = SOULX_MEL_CONFIG["hop_length"]
            sr = SOULX_MEL_CONFIG["sample_rate"]
        else:
            prior_mel = librosa.feature.melspectrogram(y=y_prior, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
    
    # Otherwise, compute both from audio.
    elif vocoder == "soulxsinger":
        prior_mel = mel_to_soulx_mel(y_prior, sr=sr)
        target_mel = mel_to_soulx_mel(y_target, sr=sr)
        # Override hop_length for frame conversion (Vocos uses 480)
        hop_length = SOULX_MEL_CONFIG["hop_length"]
        sr = SOULX_MEL_CONFIG["sample_rate"]
    else:
        prior_mel = librosa.feature.melspectrogram(y=y_prior, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
        target_mel = librosa.feature.melspectrogram(y=y_target, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
    
    # Parse TextGrids for exactly corresponding boundaries
    tier_name = "words" if segmentation_mode == "word" else "phones"
    
    def parse_tg(path):
        boundaries = []
        if os.path.exists(path):
            tg = tgt.io.read_textgrid(path)
            tier = tg.get_tier_by_name(tier_name) if tier_name in [t.name for t in tg.tiers] else tg.tiers[0]
            for interval in tier.intervals:
                # Skip MFA generated silences as they don't explicitly correspond to semantic vocal timings
                if interval.text.strip() in ["", "sp", "sil"]:
                    continue
                boundaries.append({
                    'phoneme': interval.text,
                    'start': interval.start_time,
                    'end': interval.end_time
                })
        return boundaries

    prior_boundaries_sec = parse_tg(prior_textgrid_path)
    target_boundaries_sec = parse_tg(target_textgrid_path)
    
    return prior_mel, target_mel, prior_boundaries_sec, target_boundaries_sec

def convert_timestamps_to_frames(
    boundaries_sec: List[Dict[str, float]],
    sample_rate: int,
    hop_length: int
) -> List[Dict[str, int]]:
    """
    Translates real-world timestamps into matrix column (frame) indices.
    
    Formula: Frame Index = floor(time * (sample_rate / hop_length))
    
    Args:
        boundaries_sec: List of dictionaries with 'start' and 'end' in seconds.
        sample_rate: Audio sample rate.
        hop_length: Hop length used in feature extraction.
        
    Returns:
        boundaries_frames: List of dictionaries with 'start_frame' and 'end_frame'.
    """
    boundaries_frames = []
    factor = sample_rate / hop_length
    for b in boundaries_sec:
        start_frame = int(np.floor(b['start'] * factor))
        end_frame = int(np.floor(b['end'] * factor))
        boundaries_frames.append({
            'phoneme': b.get('phoneme', ''),
            'start_frame': start_frame,
            'end_frame': end_frame
        })
    return boundaries_frames

def _match_boundaries_by_label(
    prior_boundaries: List[Dict],
    target_boundaries: List[Dict]
) -> List[Tuple[int, int]]:
    """
    Pairs prior and post boundaries by their text label using sequence alignment.

    Returns a list of (prior_idx, post_idx) pairs where labels match.
    This prevents index-shift misalignment when MFA produces slightly different
    word/phoneme counts for the two audio streams.
    """
    prior_labels = [b['phoneme'].lower() for b in prior_boundaries]
    target_labels  = [b['phoneme'].lower() for b in target_boundaries]
    matcher = SequenceMatcher(None, prior_labels, target_labels, autojunk=False)
    pairs = []
    for block in matcher.get_matching_blocks():
        for k in range(block.size):
            pairs.append((block.a + k, block.b + k))
    return pairs


def align_phonemes_dtw(
    prior_mel: np.ndarray,
    target_mel: np.ndarray,
    prior_boundaries_frames: List[Dict[str, int]],
    target_boundaries_frames: List[Dict[str, int]],
    pad_frames: int = 0,
    diagnostic_dir: Optional[str] = None,
    config: Optional[Dict[str, int]] = None,
    vocoder: str = "griffin_lim",
    align_to: str = "prior",
) -> Tuple[List[np.ndarray], List[float], List[Dict[str, int]], List[Dict[str, int]]]:
    """
    Core function that iterates through phonemes, pads boundaries, calculates alignment
    using DTW, warps one signal onto the other's timeline, and trims the padding.

    Args:
        prior_mel: Mel-spectrogram of prior audio (shape: n_mels x T_prior).
        target_mel: Mel-spectrogram of target audio (shape: n_mels x T_post).
        prior_boundaries_frames: Prior frame boundaries.
        target_boundaries_frames: Post frame boundaries.
        pad_frames: Number of frames to expand the slices by.
        diagnostic_dir: If provided, saves slices and scores here for debugging.
        config: STFT parameters for audio inversion.
        vocoder: Choice of vocoder string.
        align_to: Which timeline to warp onto.
            "prior" (v1): warps target onto prior's timeline.
            "target"  (v2): warps prior onto target's timeline.

    Returns:
        warped_slices: List of warped mel-spectrogram slices.
        local_dtw_costs: List of local DTW costs for each phoneme.
        matched_target_boundaries: Boundaries on the target timeline (for stitching).
        matched_source_boundaries: Boundaries on the source timeline (for audio warping).
    """
    warped_slices = []
    local_dtw_costs = []
    matched_target_boundaries = []
    matched_source_boundaries = []

    max_prior_len = prior_mel.shape[1]
    max_target_len = target_mel.shape[1]

    # Match boundaries by label so index-shift from MFA doesn't misalign words.
    matched_pairs = _match_boundaries_by_label(prior_boundaries_frames, target_boundaries_frames)
    if not matched_pairs:
        # Fallback: naive index pairing (original behaviour) when no labels match.
        n = min(len(prior_boundaries_frames), len(target_boundaries_frames))
        matched_pairs = [(i, i) for i in range(n)]

    print(f"  Boundary matching: {len(matched_pairs)} / {max(len(prior_boundaries_frames), len(target_boundaries_frames))} segments matched by label.")

    for seg_idx, (pi, pti) in enumerate(matched_pairs):
        pb  = prior_boundaries_frames[pi]
        ptb = target_boundaries_frames[pti]

        # 1 & 2. Expand boundaries by pad_frames (clamping at 0 and max seq len)
        prior_start = max(0, pb['start_frame'] - pad_frames)
        prior_end = min(max_prior_len, pb['end_frame'] + pad_frames)

        target_start = max(0, ptb['start_frame'] - pad_frames)
        target_end = min(max_target_len, ptb['end_frame'] + pad_frames)

        # Slicing the mel spectrograms
        prior_slice = prior_mel[:, prior_start:prior_end]
        target_slice = target_mel[:, target_start:target_end]

        # Target boundary = the timeline we're warping ONTO
        # Source boundary = the timeline we're warping FROM
        if align_to == "target":
            target_boundary = ptb
            source_boundary = pb
            target_start = target_start
            target_len = ptb['end_frame'] - ptb['start_frame']
        else:
            target_boundary = pb
            source_boundary = ptb
            target_start = prior_start
            target_len = pb['end_frame'] - pb['start_frame']

        n_mels = prior_mel.shape[0]
        if prior_slice.size <= 0 or target_slice.size <= 0 or target_len <= 0:
            zeros = np.zeros((n_mels, max(0, target_len)))
            warped_slices.append(zeros)
            local_dtw_costs.append(0.0)
            matched_target_boundaries.append(target_boundary)
            matched_source_boundaries.append(source_boundary)
            continue


        # 3. Compute DTW on padded slices
        # Sanitize NaN values (can appear in SoulX-Singer generated mels)
        if np.any(np.isnan(prior_slice)) or np.any(np.isnan(target_slice)):
            prior_slice = np.nan_to_num(prior_slice, nan=0.0)
            target_slice = np.nan_to_num(target_slice, nan=0.0)
        # Add epsilon to prevent zero-norm columns causing NaN cosine distance
        prior_slice = prior_slice + 1e-8
        target_slice = target_slice + 1e-8
        D, wp = librosa.sequence.dtw(X=prior_slice, Y=target_slice, metric='cosine')
        cost = D[-1, -1]
        local_dtw_costs.append(cost)

        wp = wp[::-1] # Reverse to get chronological order from start to end
        prior_indices = wp[:, 0]
        target_indices = wp[:, 1]

        if align_to == "target":
            # v2: Warp prior_slice onto target_slice's timeline
            pad_target_len = target_slice.shape[1]
            warped_padded = np.zeros((prior_slice.shape[0], pad_target_len))
            for j in range(prior_slice.shape[0]):
                warped_padded[j, :] = np.interp(
                    np.arange(pad_target_len), target_indices, prior_slice[j, prior_indices]
                )
        else:
            # v1: Warp target_slice onto prior_slice's timeline
            pad_target_len = prior_slice.shape[1]
            warped_padded = np.zeros((target_slice.shape[0], pad_target_len))
            for j in range(target_slice.shape[0]):
                warped_padded[j, :] = np.interp(
                    np.arange(pad_target_len), prior_indices, target_slice[j, target_indices]
                )

        # 5. CRITICAL: Trim the pad_frames off the beginning and end
        trim_start = target_boundary['start_frame'] - target_start
        trim_end = trim_start + target_len

        warped_trimmed = warped_padded[:, trim_start:trim_end]
        warped_slices.append(warped_trimmed)
        matched_target_boundaries.append(target_boundary)
        matched_source_boundaries.append(source_boundary)

        # 6. Diagnostics
        if diagnostic_dir:
            ph_name = target_boundary.get('phoneme', f'ph_{seg_idx}').replace('/', '_').replace('\\', '_')
            diag_subdir = os.path.join(diagnostic_dir, f"{seg_idx:03d}_{ph_name}")
            os.makedirs(diag_subdir, exist_ok=True)

            np.save(os.path.join(diag_subdir, "prior_slice.npy"), prior_slice)
            np.save(os.path.join(diag_subdir, "target_slice.npy"), target_slice)
            np.save(os.path.join(diag_subdir, "warped_slice.npy"), warped_trimmed)
            with open(os.path.join(diag_subdir, "dtw_score.txt"), "w") as f:
                f.write(str(cost))

            if config:
                try:
                    diag_sr = config.get("sample_rate", 22050)
                    sf.write(os.path.join(diag_subdir, "prior_slice.wav"), invert_mel_to_audio(prior_slice, config, vocoder=vocoder), diag_sr)
                    sf.write(os.path.join(diag_subdir, "target_slice.wav"), invert_mel_to_audio(target_slice, config, vocoder=vocoder), diag_sr)
                    sf.write(os.path.join(diag_subdir, "warped_slice.wav"), invert_mel_to_audio(warped_trimmed, config, vocoder=vocoder), diag_sr)
                except Exception:
                    pass  # Vocoder unavailable (e.g. torch not installed) — npy files still saved

    return warped_slices, local_dtw_costs, matched_target_boundaries, matched_source_boundaries

def stitch_warped_slices(
    warped_slices: List[np.ndarray],
    target_mel: np.ndarray,
    target_boundaries_frames: Optional[List[Dict[str, int]]] = None
) -> np.ndarray:
    """
    Reassembles warped slices into the target timeline, preserving silence gaps.

    Each warped slice is placed at the exact frame position that corresponds to its
    target boundary. Gaps between placed slices remain as zeros.

    Args:
        warped_slices: List of warped mel-spectrogram slices.
        target_mel: The mel-spectrogram whose timeline we're stitching onto.
                    For v1 (align_to="prior") this is prior_mel;
                    for v2 (align_to="target") this is target_mel.
        target_boundaries_frames: Boundaries on the target timeline to place slices at.
                                  If None, plain concatenation is used.

    Returns:
        Stitched mel aligned to target_mel's exact timeline.
    """
    if len(warped_slices) == 0:
        return np.zeros_like(target_mel)

    n_mels = target_mel.shape[0]
    total_frames = target_mel.shape[1]

    if target_boundaries_frames is not None and len(target_boundaries_frames) == len(warped_slices):
        canvas = np.zeros((n_mels, total_frames))
        for slice_mel, tb in zip(warped_slices, target_boundaries_frames):
            start = tb['start_frame']
            if start >= total_frames:
                continue
            expected_len = tb['end_frame'] - start
            fitted = slice_mel[:, :expected_len].copy()
            # Apply short boundary fade (up to 4 frames, never more than 1/4 of slice)
            fade_len = min(4, fitted.shape[1] // 4)
            if fade_len > 0:
                fade_in  = np.linspace(0.0, 1.0, fade_len)
                fade_out = np.linspace(1.0, 0.0, fade_len)
                fitted[:, :fade_len]  *= fade_in
                fitted[:, -fade_len:] *= fade_out
            end = min(start + fitted.shape[1], total_frames)
            if end <= start:
                continue
            canvas[:, start:end] = fitted[:, :end - start]
        return canvas
    else:
        # Fallback: plain concatenation (original behavior)
        final_mel = np.concatenate(warped_slices, axis=1)
        diff = total_frames - final_mel.shape[1]
        if diff > 0:
            padding = np.zeros((n_mels, diff))
            final_mel = np.concatenate([final_mel, padding], axis=1)
        elif diff < 0:
            final_mel = final_mel[:, :total_frames]
        return final_mel

def _write_alignment_meta(export_dir: str, meta: dict) -> None:
    """Write alignment.json to export_dir, merging with any existing content."""
    os.makedirs(export_dir, exist_ok=True)
    path = os.path.join(export_dir, "alignment.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)


def align_and_export_mel(
    prior_audio_path: str,
    target_audio_path: str,
    prior_textgrid_path: str,
    target_textgrid_path: str,
    config: Dict[str, int],
    pad_frames: int,
    cost_threshold: float,
    export_dir: str,
    diagnostic_mode: bool = False,
    segmentation_mode: str = "word",
    vocoder: str = "hifigan",
    target_mel_path: Optional[str] = None,
    align_to: str = "prior",
) -> bool:
    """
    Executes all pipeline steps, records alignment quality, and saves output.

    Always writes alignment.json with per-phoneme DTW scores regardless of quality.
    Always saves aligned.wav so no GPU work is silently discarded.
    cost_threshold is retained for logging/flagging only — it no longer gates file saving.

    Args:
        align_to: Which timeline to warp onto.
            "prior" (v1): warps target onto prior's timeline — aligned.wav has target's
                          timbre on prior's timing.
            "target"  (v2): warps prior onto target's timeline — aligned.wav has prior's
                          timbre on target's timing.

    Returns:
        bool: True if mean DTW cost is within cost_threshold, False otherwise.
              aligned.wav and alignment.json are written in both cases.
    """
    timestamp = datetime.now().isoformat(timespec="seconds")

    # Step 1
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Extracting features and timings...")
    prior_mel, target_mel, prior_boundaries_sec, target_boundaries_sec = extract_features_and_timings(
        prior_audio_path, target_audio_path, prior_textgrid_path, target_textgrid_path, config, segmentation_mode, vocoder, target_mel_path=target_mel_path
    )
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Feature extraction complete.")

    # Step 2 - use SoulX-Singer sample rate and hop if using that vocoder
    if vocoder == "soulxsinger":
        sr = SOULX_MEL_CONFIG["sample_rate"]
        hop_length = SOULX_MEL_CONFIG["hop_length"]
    else:
        sr = config.get("sample_rate", 22050)
        hop_length = config.get("hop_length", 256)

    prior_boundaries_frames = convert_timestamps_to_frames(prior_boundaries_sec, sr, hop_length)
    target_boundaries_frames = convert_timestamps_to_frames(target_boundaries_sec, sr, hop_length)

    # Step 3
    diag_path = os.path.join(export_dir, "diagnostics") if diagnostic_mode else None
    if diag_path:
        os.makedirs(diag_path, exist_ok=True)

    direction_label = "prior→target" if align_to == "target" else "target→prior"
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Running Phoneme-by-Phoneme DTW Alignment ({direction_label})...")
    warped_slices, local_dtw_costs, matched_target_boundaries, matched_source_boundaries = align_phonemes_dtw(
        prior_mel, target_mel, prior_boundaries_frames, target_boundaries_frames, pad_frames,
        diagnostic_dir=diag_path,
        config=config,
        vocoder=vocoder,
        align_to=align_to,
    )

    mean_cost = float(np.mean(local_dtw_costs)) if local_dtw_costs else float('inf')
    max_cost = float(np.max(local_dtw_costs)) if local_dtw_costs else float('inf')
    under_threshold = mean_cost <= cost_threshold

    # Step 4 — stitch warped slices onto the target timeline.
    target_mel = target_mel if align_to == "target" else prior_mel
    final_warped_mel = stitch_warped_slices(warped_slices, target_mel, matched_target_boundaries)

    os.makedirs(export_dir, exist_ok=True)

    if align_to == "target":
        # v2: Time-stretch the prior AUDIO onto the target timeline per segment.
        # We avoid mel→vocoder inversion because the vocoder (e.g. Vocos) was
        # trained on target's mel space and produces artifacts on prior's mel.
        # librosa.effects.time_stretch preserves pitch while adjusting duration.
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Time-stretching prior audio onto target timeline...")
        y_prior, _ = librosa.load(prior_audio_path, sr=sr)
        y_target, _ = librosa.load(target_audio_path, sr=sr)

        canvas = np.zeros(len(y_target), dtype=np.float32)
        for tb, sb in zip(matched_target_boundaries, matched_source_boundaries):
            # tb = post boundary (target), sb = prior boundary (source)
            target_start_samp = int(tb['start_frame'] * hop_length)
            target_end_samp = int(tb['end_frame'] * hop_length)
            prior_start_samp = int(sb['start_frame'] * hop_length)
            prior_end_samp = int(sb['end_frame'] * hop_length)

            post_seg_len = target_end_samp - target_start_samp
            prior_seg = y_prior[prior_start_samp:min(prior_end_samp, len(y_prior))]

            if len(prior_seg) < 2048 or post_seg_len < 2048:
                continue

            # Time-stretch preserves pitch: rate > 1 = faster, rate < 1 = slower
            prior_dur = len(prior_seg)
            rate = prior_dur / post_seg_len
            rate = np.clip(rate, 0.1, 10.0)  # safety bounds

            stretched = librosa.effects.time_stretch(prior_seg, rate=rate)

            # Fit stretched audio to exact target length
            if len(stretched) >= post_seg_len:
                fitted = stretched[:post_seg_len]
            else:
                fitted = np.pad(stretched, (0, post_seg_len - len(stretched)))

            # Crossfade at boundaries to prevent clicks (8ms ramp)
            fade_len = min(int(0.008 * sr), len(fitted) // 4)
            if fade_len > 0:
                fitted[:fade_len] *= np.linspace(0, 1, fade_len)
                fitted[-fade_len:] *= np.linspace(1, 0, fade_len)

            end = min(target_start_samp + post_seg_len, len(canvas))
            n_copy = end - target_start_samp
            if n_copy > 0:
                canvas[target_start_samp:end] = fitted[:n_copy]

        aligned_audio = canvas

        # Also save the warped prior mel for training use
        mel_path = os.path.join(export_dir, "aligned_mel.npy")
        np.save(mel_path, final_warped_mel)
    else:
        # v1: Invert warped post mel to audio using the selected vocoder.
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Inverting mel-spectrogram to audio via {vocoder}...")
        aligned_audio = invert_mel_to_audio(final_warped_mel, config, vocoder=vocoder)

    # Export audio — always saved regardless of cost
    out_path = os.path.join(export_dir, "aligned.wav")
    sf.write(out_path, aligned_audio, sr)

    # Write per-line alignment metadata
    _write_alignment_meta(export_dir, {
        "mean_dtw_cost": round(mean_cost, 4),
        "max_dtw_cost": round(max_cost, 4),
        "per_phoneme_costs": [round(c, 4) for c in local_dtw_costs],
        "n_phonemes_aligned": len(local_dtw_costs),
        "n_phonemes_total": max(len(prior_boundaries_frames), len(target_boundaries_frames)),
        "under_threshold": under_threshold,
        "cost_threshold": cost_threshold,
        "mfa_prior_ok": True,
        "mfa_target_ok": True,
        "aligned_saved": True,
        "align_to": align_to,
        "segmentation_mode": segmentation_mode,
        "vocoder": vocoder,
        "timestamp": timestamp,
    })

    if under_threshold:
        print(f"Alignment successful (mean={mean_cost:.2f}, max={max_cost:.2f}). Saved to {out_path}")
    else:
        print(f"Alignment saved but flagged (mean={mean_cost:.2f} > threshold={cost_threshold}). Saved to {out_path}")

    return under_threshold
