import os
import numpy as np
import librosa
import tgt
import soundfile as sf
from typing import List, Dict, Tuple, Optional
from vocoders import invert_mel_to_audio, mel_to_soulx_mel, SOULX_MEL_CONFIG

def extract_features_and_timings(
    prior_audio_path: str,
    post_audio_path: str,
    prior_textgrid_path: str,
    post_textgrid_path: str,
    config: Dict[str, int],
    segmentation_mode: str = "word",
    vocoder: str = "griffin_lim",
    post_mel_path: Optional[str] = None
) -> Tuple[np.ndarray, np.ndarray, List[Dict[str, float]], List[Dict[str, float]]]:
    """
    Loads audio, computes mel-spectrograms, and parses timing data.
    
    Args:
        prior_audio_path: Path to the prior audio file (e.g., OpenUtau output).
        post_audio_path: Path to the post audio file (e.g., SoulX-Singer output).
        prior_timings: Engine timings, e.g., [{'phoneme': 'a', 'start': 0.1, 'end': 0.3}].
        post_textgrid_path: Path to the MFA-generated TextGrid. (Optional)
        config: STFT parameters (sample_rate, n_fft, hop_length, n_mels).
        
    Returns:
        prior_mel: Mel-spectrogram of the prior audio (shape: mels x time).
        post_mel: Mel-spectrogram of the post audio.
        prior_boundaries_sec: List of dictionaries with phoneme boundaries in seconds.
        post_boundaries_sec: List of dictionaries with phoneme boundaries in seconds.
    """
    sr = config.get("sample_rate", 22050)
    n_fft = config.get("n_fft", 1024)
    hop_length = config.get("hop_length", 256)
    n_mels = config.get("n_mels", 80)
    
    y_prior, _ = librosa.load(prior_audio_path, sr=sr)
    y_post, _ = librosa.load(post_audio_path, sr=sr)
    
    # When using a pre-extracted mel (e.g., from SoulX-Singer's generator), load it directly.
    if post_mel_path and os.path.exists(post_mel_path):
        print(f"Loading pre-extracted post-mel from {post_mel_path}...")
        post_mel = np.load(post_mel_path)
        # Should be (Time, Mels) as generated by SoulX CLI, so transpose if needed.
        if post_mel.shape[1] == 128:
            post_mel = post_mel.T
        
        # We still need to extract prior_mel
        if vocoder == "soulxsinger":
            prior_mel = mel_to_soulx_mel(y_prior, sr=sr)
            hop_length = SOULX_MEL_CONFIG["hop_length"]
            sr = SOULX_MEL_CONFIG["sample_rate"]
        else:
            prior_mel = librosa.feature.melspectrogram(y=y_prior, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
    
    # Otherwise, compute both from audio.
    elif vocoder == "soulxsinger":
        prior_mel = mel_to_soulx_mel(y_prior, sr=sr)
        post_mel = mel_to_soulx_mel(y_post, sr=sr)
        # Override hop_length for frame conversion (Vocos uses 480)
        hop_length = SOULX_MEL_CONFIG["hop_length"]
        sr = SOULX_MEL_CONFIG["sample_rate"]
    else:
        prior_mel = librosa.feature.melspectrogram(y=y_prior, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
        post_mel = librosa.feature.melspectrogram(y=y_post, sr=sr, n_fft=n_fft, hop_length=hop_length, n_mels=n_mels)
    
    # Parse TextGrids for exactly corresponding boundaries
    tier_name = "words" if segmentation_mode == "word" else "phones"
    
    def parse_tg(path):
        boundaries = []
        if os.path.exists(path):
            tg = tgt.io.read_textgrid(path)
            tier = tg.get_tier_by_name(tier_name) if tier_name in [t.name for t in tg.tiers] else tg.tiers[0]
            for interval in tier.intervals:
                # Skip MFA generated silences as they don't explicitly correspond to semantic vocal timings
                if interval.text.strip() in ["", "sp", "sil"]:
                    continue
                boundaries.append({
                    'phoneme': interval.text,
                    'start': interval.start_time,
                    'end': interval.end_time
                })
        return boundaries

    prior_boundaries_sec = parse_tg(prior_textgrid_path)
    post_boundaries_sec = parse_tg(post_textgrid_path)
    
    return prior_mel, post_mel, prior_boundaries_sec, post_boundaries_sec

def convert_timestamps_to_frames(
    boundaries_sec: List[Dict[str, float]],
    sample_rate: int,
    hop_length: int
) -> List[Dict[str, int]]:
    """
    Translates real-world timestamps into matrix column (frame) indices.
    
    Formula: Frame Index = floor(time * (sample_rate / hop_length))
    
    Args:
        boundaries_sec: List of dictionaries with 'start' and 'end' in seconds.
        sample_rate: Audio sample rate.
        hop_length: Hop length used in feature extraction.
        
    Returns:
        boundaries_frames: List of dictionaries with 'start_frame' and 'end_frame'.
    """
    boundaries_frames = []
    factor = sample_rate / hop_length
    for b in boundaries_sec:
        start_frame = int(np.floor(b['start'] * factor))
        end_frame = int(np.floor(b['end'] * factor))
        boundaries_frames.append({
            'phoneme': b.get('phoneme', ''),
            'start_frame': start_frame,
            'end_frame': end_frame
        })
    return boundaries_frames

def align_phonemes_dtw(
    prior_mel: np.ndarray,
    post_mel: np.ndarray,
    prior_boundaries_frames: List[Dict[str, int]],
    post_boundaries_frames: List[Dict[str, int]],
    pad_frames: int = 0,
    diagnostic_dir: Optional[str] = None,
    config: Optional[Dict[str, int]] = None,
    vocoder: str = "griffin_lim"
) -> Tuple[List[np.ndarray], List[float]]:
    """
    Core function that iterates through phonemes, pads boundaries, calculates alignment 
    using DTW, warps the post slice, and trims the padding.
    
    Args:
        prior_mel: Mel-spectrogram of prior audio (shape: n_mels x T_prior).
        post_mel: Mel-spectrogram of post audio (shape: n_mels x T_post).
        prior_boundaries_frames: Prior frame boundaries.
        post_boundaries_frames: Post frame boundaries.
        pad_frames: Number of frames to expand the slices by.
        diagnostic_dir: If provided, saves slices and scores here for debugging.
        config: STFT parameters for audio inversion.
        vocoder: Choice of vocoder string.
        
    Returns:
        warped_post_slices: List of warped mel-spectrogram slices.
        local_dtw_costs: List of local DTW costs for each phoneme.
    """
    warped_post_slices = []
    local_dtw_costs = []
    
    max_prior_len = prior_mel.shape[1]
    max_post_len = post_mel.shape[1]
    
    num_phonemes = min(len(prior_boundaries_frames), len(post_boundaries_frames))
    
    for i in range(num_phonemes):
        pb = prior_boundaries_frames[i]
        ptb = post_boundaries_frames[i]
        
        # 1 & 2. Expand boundaries by pad_frames (clamping at 0 and max seq len)
        prior_start = max(0, pb['start_frame'] - pad_frames)
        prior_end = min(max_prior_len, pb['end_frame'] + pad_frames)
        
        post_start = max(0, ptb['start_frame'] - pad_frames)
        post_end = min(max_post_len, ptb['end_frame'] + pad_frames)
        
        # Slicing the mel spectrograms
        prior_slice = prior_mel[:, prior_start:prior_end]
        post_slice = post_mel[:, post_start:post_end]
        
        target_len = pb['end_frame'] - pb['start_frame']
        
        if prior_slice.size <= 0 or post_slice.size <= 0 or target_len <= 0:
            # Fallback for empty lengths due to edge cases/silences
            zeros = np.zeros((post_mel.shape[0], max(0, target_len)))
            warped_post_slices.append(zeros)
            local_dtw_costs.append(0.0)
            continue

        
        # 3. Compute DTW on padded slices
        D, wp = librosa.sequence.dtw(X=prior_slice, Y=post_slice, metric='cosine')
        cost = D[-1, -1]
        local_dtw_costs.append(cost)
        
        wp = wp[::-1] # Reverse to get chronological order from start to end
        
        # 4. Warp the padded post_slice to match prior_slice time dimension
        pad_prior_len = prior_slice.shape[1]
        prior_indices = wp[:, 0]
        post_indices = wp[:, 1]
        
        warped_padded_post = np.zeros((post_slice.shape[0], pad_prior_len))
        for j in range(post_slice.shape[0]):
            # Interpolate post mel frame values aligned to prior timeline
            warped_padded_post[j, :] = np.interp(np.arange(pad_prior_len), prior_indices, post_slice[j, post_indices])

        # 5. CRITICAL: Trim the pad_frames off the beginning and end
        # Define the actual target boundaries inside the padded warped post
        trim_start = pb['start_frame'] - prior_start
        trim_end = trim_start + target_len
        
        # Extract strictly the intended target boundary length
        warped_trimmed = warped_padded_post[:, trim_start:trim_end]
        warped_post_slices.append(warped_trimmed)
        
        # 6. Diagnostics
        if diagnostic_dir:
            ph_name = pb.get('phoneme', f'ph_{i}').replace('/', '_').replace('\\', '_')
            diag_subdir = os.path.join(diagnostic_dir, f"{i:03d}_{ph_name}")
            os.makedirs(diag_subdir, exist_ok=True)
            
            np.save(os.path.join(diag_subdir, "prior_slice.npy"), prior_slice)
            np.save(os.path.join(diag_subdir, "post_slice.npy"), post_slice)
            np.save(os.path.join(diag_subdir, "warped_post_slice.npy"), warped_trimmed)
            with open(os.path.join(diag_subdir, "dtw_score.txt"), "w") as f:
                f.write(str(cost))
            
            if config:
                sr = config.get("sample_rate", 22050)
                sf.write(os.path.join(diag_subdir, "prior_slice.wav"), invert_mel_to_audio(prior_slice, config, vocoder=vocoder), sr)
                sf.write(os.path.join(diag_subdir, "post_slice.wav"), invert_mel_to_audio(post_slice, config, vocoder=vocoder), sr)
                sf.write(os.path.join(diag_subdir, "warped_post_slice.wav"), invert_mel_to_audio(warped_trimmed, config, vocoder=vocoder), sr)
        
    return warped_post_slices, local_dtw_costs

def stitch_warped_slices(
    warped_post_slices: List[np.ndarray],
    prior_mel: np.ndarray,
    prior_boundaries_frames: Optional[List[Dict[str, int]]] = None
) -> np.ndarray:
    """
    Reassembles the warped slices into the full prior timeline, preserving silence gaps.
    
    Each warped slice is placed at the exact frame position that corresponds to its prior
    word/phoneme boundary, so pre-word silence, inter-word silence, and post-word silence
    are all preserved from the prior audio. Gaps between placed slices remain as zeros.
    
    Args:
        warped_post_slices: List of warped post mel-spectrogram slices.
        prior_mel: The target prior mel-spectrogram matrix.
        prior_boundaries_frames: Optionally provide prior boundaries to place slices at 
                                  correct positions. If None, plain concatenation is used.
        
    Returns:
        final_warped_post_mel: Mel aligned to prior_mel's exact timeline.
    """
    if len(warped_post_slices) == 0:
        return np.zeros_like(prior_mel)
    
    n_mels = prior_mel.shape[0]
    total_frames = prior_mel.shape[1]
    
    if prior_boundaries_frames is not None and len(prior_boundaries_frames) == len(warped_post_slices):
        # Place each warped slice at its exact prior position on a silent canvas
        canvas = np.zeros((n_mels, total_frames))
        for slice_mel, pb in zip(warped_post_slices, prior_boundaries_frames):
            start = pb['start_frame']
            expected_len = pb['end_frame'] - start
            # Clip the slice to the expected length (safety guard)
            fitted = slice_mel[:, :expected_len]
            end = min(start + fitted.shape[1], total_frames)
            canvas[:, start:end] = fitted[:, :end - start]
        return canvas
    else:
        # Fallback: plain concatenation (original behavior)
        final_warped_post_mel = np.concatenate(warped_post_slices, axis=1)
        diff = total_frames - final_warped_post_mel.shape[1]
        if diff > 0:
            padding = np.zeros((n_mels, diff))
            final_warped_post_mel = np.concatenate([final_warped_post_mel, padding], axis=1)
        elif diff < 0:
            final_warped_post_mel = final_warped_post_mel[:, :total_frames]
        return final_warped_post_mel

def align_and_export_mel(
    prior_audio_path: str,
    post_audio_path: str,
    prior_textgrid_path: str,
    post_textgrid_path: str,
    config: Dict[str, int],
    pad_frames: int,
    cost_threshold: float,
    export_dir: str,
    diagnostic_mode: bool = False,
    segmentation_mode: str = "word",
    vocoder: str = "hifigan",
    post_mel_path: Optional[str] = None
) -> bool:
    """
    Executes all pipeline steps, evaluates alignment mathematically, and saves output.
    
    Args:
        prior_audio_path: Path to the prior audio file.
        post_audio_path: Path to the post audio file.
        prior_textgrid_path: Path to the Prior MFA-generated TextGrid.
        post_textgrid_path: Path to the Post MFA-generated TextGrid.
        config: STFT parameters.
        pad_frames: Frames parameter for micro-dtw padding.
        cost_threshold: Threshold for DTW mean cost rejection.
        export_dir: Directory to save the `.wav` output.
        diagnostic_mode: If True, exports phoneme-by-phoneme slices and scores.
        segmentation_mode: "word" or "phoneme" DTW granularity.
        vocoder: "griffin_lim" or "hifigan" backend.
    
    Returns:
        bool: True if alignment is successful and under the cost threshold, False otherwise.
    """
    # Step 1
    prior_mel, post_mel, prior_boundaries_sec, post_boundaries_sec = extract_features_and_timings(
        prior_audio_path, post_audio_path, prior_textgrid_path, post_textgrid_path, config, segmentation_mode, vocoder, post_mel_path=post_mel_path
    )
    
    # Step 2 - use SoulX-Singer sample rate and hop if using that vocoder
    if vocoder == "soulxsinger":
        sr = SOULX_MEL_CONFIG["sample_rate"]
        hop_length = SOULX_MEL_CONFIG["hop_length"]
    else:
        sr = config.get("sample_rate", 22050)
        hop_length = config.get("hop_length", 256)
    
    prior_boundaries_frames = convert_timestamps_to_frames(prior_boundaries_sec, sr, hop_length)
    post_boundaries_frames = convert_timestamps_to_frames(post_boundaries_sec, sr, hop_length)
    
    # Step 3
    diag_path = os.path.join(export_dir, "diagnostics") if diagnostic_mode else None
    if diag_path:
        os.makedirs(diag_path, exist_ok=True)
        
    warped_post_slices, local_dtw_costs = align_phonemes_dtw(
        prior_mel, post_mel, prior_boundaries_frames, post_boundaries_frames, pad_frames,
        diagnostic_dir=diag_path,
        config=config,
        vocoder=vocoder
    )
    
    # Quality Assurance Evaluation
    mean_cost = float(np.mean(local_dtw_costs)) if local_dtw_costs else float('inf')
    if mean_cost > cost_threshold:
        print(f"Alignment rejected! Mean DTW cost {mean_cost:.2f} > threshold {cost_threshold}")
        return False
        
    # Step 4 — place each warped slice at its exact prior frame position
    final_warped_post_mel = stitch_warped_slices(warped_post_slices, prior_mel, prior_boundaries_frames)
    
    # Invert to audio using the selected Vocoder
    aligned_audio = invert_mel_to_audio(final_warped_post_mel, config, vocoder=vocoder)
    
    # Export
    os.makedirs(export_dir, exist_ok=True)
    out_path = os.path.join(export_dir, "aligned.wav")
    
    sf.write(out_path, aligned_audio, sr)
    
    print(f"Alignment successful (Cost: {mean_cost:.2f}). Saved to {out_path}")
    return True
